name: I Search Marketing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38594
title: 'I Search Marketing | Ethnic Marketing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#544f56'
    - '#74d6d7'
    - '#4d8a8b'
    - '#adc400'
    - '#00b4de'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
